sm_thngs_proj/Employee_accounts/urls.py
from django.conf.urls import url
from . import views



urlpatterns = (
    # urls for Employee
    url(r'^employee/$', views.EmployeeListView.as_view(), name='Employee_accounts_employee_list'),
   )

#which means we can append more urls that can be specific to any apps
urlpatterns += (
    # urls for Employee
    url(r'^list/$', views.EmployeeListView.as_view(), name='Employee_accounts_employee_list'),
    #url(r'^employee/list/$', views.employeelistview, name='employeelistview'),

    url(r'^create/$', views.EmployeeCreateView.as_view(), name='Employee_accounts_employee_create'),
    #url(r'^employee/create/$', views.employeecreateview, name='employeecreateview'),

    url(r'^detail/(?P<slug>\S+)/$', views.EmployeeDetailView.as_view(), name='Employee_accounts_employee_detail'),
    url(r'^update/(?P<slug>\S+)/$', views.EmployeeUpdateView.as_view(), name='Employee_accounts_employee_update'),
)


#ALL FORMS URL
urlpatterns += (

    url(r'^greetform/$', views.greetform, name='greetform'),

)

sm_thngs_proj/author/urls.py
from django.conf.urls import url
from . import views



urlpatterns = (
    # urls for Author
    url(r'^list/$', views.authorListView, name='authorListView'),

    url(r'^create/$', views.authorCreateView, name='authorCreateView'),

    url(r'^detail/(?P<pk>[0-9])/$', views.authorDetailView, name='authorDetailView'),

    url(r'^update/(?P<slug>\S+)/$', views.authorUpdateView, name='authorUpdateView'),
)

sm_thngs_proj/sm_thngs_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('Employee_accounts.urls', namespace='accounts')),
]

urlpatterns += [
    url(r'^author/', include('author.urls', namespace='author')),
]
              # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) <-- we can add this but what is this for??

urlpatterns += [
    url(r'^admin/', admin.site.urls),
]

sm_thngs_proj/Employee_accounts/models.py
from django.core.urlresolvers import reverse
from django_extensions.db.fields import AutoSlugField
from django.db.models import *
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.contrib.auth import models as auth_models
from django.db import models as models
from django_extensions.db import fields as extension_fields


class Employee(models.Model):

    # Fields
    f_name = models.CharField(max_length=50)
    l_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20, null=False)
    website = models.URLField(max_length=50, null=True)
    address = models.CharField(max_length=255, null=False)
    about = models.TextField(max_length=500, null=False)
    slug = extension_fields.AutoSlugField(unique=True, populate_from='f_name')
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return u'%s' % self.slug

    def get_absolute_url(self):
        return reverse('accounts:Employee_accounts_employee_detail', args=(self.slug,))


    def get_update_url(self):
        return reverse('accounts:Employee_accounts_employee_update', args=(self.slug,))



#creating subclass(Developer) that inherits from parent class(Employee)
# class Developer(Employee):
# we can have normal class topics in this as this is models.py and only database models are suppose to be here.
#we are going to create a seprate package to test classes and methods in them and how to inherit from a class and override any of it's behaviour

sm_thngs_proj/author/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=100, unique=True)
    email = models.EmailField(unique=True)
    active = models.BooleanField(default=False)
    created_on = models.DateTimeField()
    last_logged_in = models.DateTimeField()


    class Meta:
        ordering = ('-pk',)

    def __str__(self):
        return u'%s' % self.name

    def get_absolute_url(self):
        return reverse('accounts:author_accounts_employee_detail', args=(self.pk,))


    def get_update_url(self):
        return reverse('accounts:Employee_accounts_employee_update', args=(self.slug,))

sm_thngs_proj/Employee_accounts/forms.py
from django import forms
from .models import Employee


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['f_name', 'l_name']

sm_thngs_proj/author/forms.py
from django import forms

class AuthorForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    active = forms.BooleanField(required=False) # required=False makes the field optional
    created_on = forms.DateTimeField()
    last_logged_in = forms.DateTimeField()

sm_thngs_proj/Employee_accounts/views.py
from django.views.generic import DetailView, ListView, UpdateView, CreateView
from .models import Employee
from .forms import EmployeeForm
from django.shortcuts import render, HttpResponse


class EmployeeListView(ListView):
    model = Employee
    template_name = 'Employee_accounts/employee_list_func.html'
    context_object_name = 'all_emp'

    #how to override querying database
    # def get_queryset(self):
    #     all_emp = Employee.objects.filter(f_name='test_fname')

def employeelistview(request):
    all_emp = Employee.objects.all()
    return render(request, template_name='Employee_accounts/employee_list.html', context={'object_list':all_emp})


class EmployeeCreateView(CreateView):
    model = Employee
    form_class = EmployeeForm

def employeecreateview(request):
    if request.mehtod =='GET':
        form  = EmployeeForm()
    if request.mehtod =='POST':
        pass

class EmployeeDetailView(DetailView):
    model = Employee


class EmployeeUpdateView(UpdateView):
    model = Employee
    form_class = EmployeeForm

#all forms
def greetform(request):
    if request.method == 'GET':
        print(request)
        return render(request, template_name='test_forms.html')

    else:
        # print(dir(POST.DATA)) ## HOW TO CAPTURE DATA THAT'S COMMING FROM FORM USING POST METHOD
        return render(request, template_name='test_forms.html', context={'object_list': 'i am here as context value'})

sm_thngs_proj/author/views.py
from django.shortcuts import render

# Create your views here.
def authorListView(request):
    pass

def authorCreateView(request):
    pass

def authorDetailView(request):
    pass

def authorUpdateView(request):
    pass

sm_thngs_proj/Employee_accounts/templates/Employee_accounts/employee_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'accounts:Employee_accounts_employee_list' %}">Employee Listing</a></p>
<table class="table">
<tr><td>name</td><td>{{ object.name }}</td></tr>
<tr><td>slug</td><td>{{ object.slug }}</td></tr>
<tr><td>created</td><td>{{ object.created }}</td></tr>
<tr><td>last_updated</td><td>{{ object.last_updated }}</td></tr>
</table>
<a class="btn btn-primary" href="{{object.get_update_url}}">Edit Employee</a>

{% endblock %}

sm_thngs_proj/Employee_accounts/templates/Employee_accounts/employee_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'accounts:Employee_accounts_employee_list' %}">Employee Listing</a></p>
<form method="post">
{% csrf_token %}
{{form}}
<button class="btn btn-primary" type="submit">Submit</button>
</form>
{% endblock %}

sm_thngs_proj/Employee_accounts/templates/Employee_accounts/employee_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p><a class="btn btn-default" href="{% url 'accounts:Employee_accounts_employee_list' %}">Employee Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>name</td>
    <td>slug</td>
    <td>created</td>
    <td>last_updated</td>
</tr>

{% if object_list %}
    {% for object in object_list %}
    <tr>
        <td>{{object.pk}}</td>
        <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
        <td>{{ object.name }}</td>
        <td>{{ object.slug }}</td>
        <td>{{ object.created }}</td>
        <td>{{ object.last_updated }}</td>
    </tr>
    {% endfor %}
{% endif %}
</table><a class="btn btn-primary" href="{% url 'accounts:Employee_accounts_employee_create' %}">Create new Employee</a>
{% endblock %}

sm_thngs_proj/Employee_accounts/templates/Employee_accounts/employee_list_func.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2>template_name in class worked!!</h2>
<p><a class="btn btn-default" href="{% url 'accounts:Employee_accounts_employee_list' %}">Employee Listing</a></p>
<table class="table">
<tr>
<td>ID</td><td>Link</td>
    <td>name</td>
    <td>slug</td>
    <td>created</td>
    <td>last_updated</td>
</tr>

{% if object_list %}
    {% for object in all_emp %}
    <tr>
        <td>{{object.pk}}</td>
        <td><a href="{{object.get_absolute_url}}">{{object}}</a></td>
        <td>{{ object.name }}</td>
        <td>{{ object.slug }}</td>
        <td>{{ object.created }}</td>
        <td>{{ object.last_updated }}</td>
    </tr>
    {% endfor %}
{% endif %}
</table><a class="btn btn-primary" href="{% url 'accounts:Employee_accounts_employee_create' %}">Create new Employee</a>
{% endblock %}

sm_thngs_proj/Employee_accounts/templates/base.html
<html><head></head><body>{% block content %}Replace this.{% endblock %}</body>

sm_thngs_proj/Employee_accounts/templates/test_forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test_forms</title>
</head>
<body>
    <form action="" method="post" name="greet_form">
        {% csrf_token %}
        <h1>Put the asked details here</h1>
        <input type="text" placeholder="Put your name here">
        <button type="submit">SUMIT!</button>
    </form>
</body>
</html>

sm_thngs_proj/author/templates/author/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author_list</title>
</head>
<body>

</body>
</html>

sm_thngs_proj/author/templates/author/author_model_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Author_model_form</title>
</head>
<body>
    <form action="" method="post">
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</body>
</html>